spring:
  config:
    activate:
      on-profile: qa

loan:
  message: Welcome to EazyBank Card related local APIs in QA Environment
  contactDetails:
    name: Jame Paul - Developer
    email: jamespaul@eazybank.com
  onCallSupport:
    - (599) 555-1274
    - (399) 523-1365
