spring:
  application:
    name: loan
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      - application_prod.yml
      - application_qa.yml
  profiles:
    active: qa

server:
  port: 8090

build:
  version: 1.0

loan:
  message: Welcome to EazyBank Loan related local APIs
  contactDetails:
    name: Ibrahim Lokua - Developer
    email: ibrahlokua@eazybank.com
  onCallSupport:
    - (551) 555-1244
    - (551) 523-1341
